#!/bin/bash

# Zundamon Voice Bot Ecosystem - macOS Automated Installer
# This script automatically guides the user to set up .env and install dependencies.

cd "$(dirname "$0")"

echo "================================================="
echo "  ずんだもんボット (Zundamon Voice) セットアップ"
echo "================================================="
echo

if ! command -v node &> /dev/null; then
    echo "[エラー] Node.jsがインストールされていません。 https://nodejs.org/ からインストールしてください。"
    exit 1
fi

echo "--- [ セクション 1: データベース (Supabase) ] ---"
echo "Supabaseはボットの設定保存や、二段階認証(2FA)に必要です。"
echo
echo "[?] まだプロジェクトを作成していない場合:"
echo "  1. https://supabase.com/dashboard にアクセスしてログインします。"
echo "  2. 「New Project」をクリックします。"
echo "  3. 以下の設定が推奨されます："
echo "     - Region: ボットを動かす場所に近い地域 (例: Tokyo など)"
echo "     - Database Password: 忘れないようにメモしてください"
echo "     - Pricing: 「Free」プランで十分です"
echo

echo "▶ Supabase プロジェクトURL の取得方法:"
echo "  1. https://supabase.com/dashboard にアクセスしてプロジェクトを選択します。"
echo "  2. プロジェクトの「Overview」または「Settings > API」を開きます。"
echo "  3. 「Project URL」の部分にあるURLをコピーしてください。"
read -p "▶ Supabase プロジェクトURL: " supa_url_input

echo
echo "▶ Supabase Secret API Key の取得方法:"
echo "  1. 左にある「Project Settings（ギアアイコン）」に入り「API Keys」メニューページを開きます。"
echo "  2. 「Secret keys」の右側にある「Copy API Key」を押してコピーしてください。"
read -p "▶ Supabase Secret API Key: " supa_key

# Robust Project ID extraction
if [[ $supa_url_input == *".supabase.co"* ]]; then
    # Domain: https://xyz.supabase.co
    project_id=$(echo $supa_url_input | cut -d'/' -f3 | cut -d'.' -f1)
elif [[ $supa_url_input == *"/project/"* ]]; then
    # Dashboard: https://supabase.com/dashboard/project/xyz
    project_id=$(echo $supa_url_input | awk -F'/' '{print $NF}')
fi

# Open Supabase SQL Editor helper
echo
echo "[自動操作] ブラウザで Supabase SQL エディタを開きますか？"
read -p "エンターキーを押すと開きます (スキップする場合は Ctrl+C 以外を入力): " dummy
if [ ! -z "$project_id" ]; then
    start "https://supabase.com/dashboard/project/$project_id/sql/new" 2>/dev/null || open "https://supabase.com/dashboard/project/$project_id/sql/new" 2>/dev/null
fi

echo
echo "--- [ Supabase テーブル作成用 SQL ] ---"
echo "以下の SQL をコピーして、開いた SQL エディタに貼り付けて実行(Run)してください："
echo "--------------------------------------------------"
cat <<'SQL'
CREATE TABLE IF NOT EXISTS guild_configs (
    guild_id TEXT PRIMARY KEY,
    name TEXT,
    icon_url TEXT,
    owner_id TEXT,
    member_count INTEGER,
    permissions JSONB,
    settings JSONB DEFAULT '{}'::jsonb,
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS guild_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL,
    snapshot_at TIMESTAMPTZ DEFAULT NOW(),
    texts_spoken INTEGER DEFAULT 0,
    ai_queries INTEGER DEFAULT 0,
    voice_minutes INTEGER DEFAULT 0,
    errors INTEGER DEFAULT 0,
    members_active INTEGER DEFAULT 0,
    commands_used JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS logs_v2 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT,
    type TEXT,
    message TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_settings (
    user_id TEXT PRIMARY KEY,
    settings JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS (Row Level Security) の有効化
-- Botやダッシュボード（Secret API Key使用）は引き続き全アクセス可能ですが、
-- 外部（Anon Keyなど）からの不正アクセスを防止します。
ALTER TABLE guild_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE guild_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs_v2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
SQL
echo "--------------------------------------------------"
echo "実行が完了したら、この画面に戻ってエンターキーを押してください。"
read -p ""

echo
echo "--- [ セクション 2: Discord 認証情報 ] ---"
echo

read -p "▶ Discord Bot トークン: " bot_token
echo "   (※重要: Developer Portalの「Bot」タブ最下部で 'Message Content Intent' をオンにしてください)"

echo
echo "[💡 推奨設定: Botのサーバー招待URLの作成]"
echo "  1. 左メニュー「OAuth2」 > 「URL Generator」を開きます。"
echo "  2. SCOPES: 「bot」と「applications.commands」にチェック。"
echo "  3. BOT PERMISSIONS: 以下をオンにします："
echo "     - Send Messages, Manage Messages, Read Message History"
echo "     - Connect, Speak, Use Voice Activity"
echo "  4. 生成されたURLをブラウザで開き、自分のサーバーにボットを招待してください。"
echo
read -p "▶ Discord Client ID (Application ID): " client_id
read -p "▶ あなたの Discord ユーザーID: " owner_id

echo
echo "--- [ セクション 3: メール送信設定 (SMTP) ] ---"
echo "ボットが新しいサーバーに参加した際の認証コード送信に使用します。"
echo "(後で手動で設定する場合は、何も入力せずにエンターを押してください)"
echo

while true; do
    read -p "▶ Gmail アドレス: " gmail_addr
    if [[ $gmail_addr == *@gmail.com ]]; then
        break
    fi
    echo "❌ エラー: Gmail アドレス (@gmail.com) を入力してください。"
done

owner_email=$gmail_addr
smtp_user=$gmail_addr

echo
echo "[自動操作] ブラウザで Google アプリパスワード設定ページを開きますか？"
read -p "エンターキーを押すと開きます: " dummy
start "https://myaccount.google.com/apppasswords" 2>/dev/null || open "https://myaccount.google.com/apppasswords" 2>/dev/null

echo "▶ Gmail アプリパスワード"
echo "  (※Google設定 > セキュリティ > 2段階認証 > アプリパスワード から取得した16桁のコード)"
read -p "  入力: " smtp_pass

# .env ファイルの生成
cat <<EOF > .env
# ── Required ─────────────────────────────────────

# ── Supabase (Required for Database/2FA) ─────────
SUPABASE_URL=$supa_url_input
SUPABASE_KEY=$supa_key

# ── Discord ───────────────────────────────────────
DISCORD_TOKEN=$bot_token
CLIENT_ID=$client_id
OWNER_DISCORD_ID=$owner_id

# ── Email / SMTP ──────────────────────────────────
OWNER_EMAIL=$owner_email
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=$smtp_user
SMTP_PASS=$smtp_pass

# ── Ollama (Local AI) ─────────────────────────────
OLLAMA_URL=http://localhost:11434
OLLAMA_MODEL=qwen2.5:7b

# ── VoiceVox (TTS Engine) ─────────────────────────
VOICEVOX_URL=http://localhost:50021
VOICEVOX_SPEAKER=3
EOF

echo
echo "✅ .env ファイルを作成しました。"
echo

echo "[依存パッケージのインストール]"
npm install

echo
echo "[スラッシュコマンドの登録]"
node deploy-commands.js

# 実行権限の付与
chmod +x StartZundamon.command ShutdownZundamon.command 2>/dev/null

echo
echo "================================================="
echo " 🎉 セットアップがすべて完了しました！"
echo "================================================="
echo "今後は「StartZundamon.command」をダブルクリックして起動してください。"
echo

read -p "エンターキーを押すと終了します..."
